# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json

name: build
on:
  workflow_dispatch:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
  DOTNET_NOLOGO: true
  GitHubUsername: NF-Software-Inc

defaults:
  run:
    shell: pwsh

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: true
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Install dependencies main
      run: dotnet restore
      working-directory: ./Easy-Logger
    - name: Build main
      run: dotnet build --configuration Release
      working-directory: ./Easy-Logger
    - name: Install dependencies Blazor
      run: dotnet restore
      working-directory: ./Easy-Logger-Blazor
    - name: Build Blazor
      run: dotnet build --configuration Release
      working-directory: ./Easy-Logger-Blazor
    - name: Install dependencies SQL
      run: dotnet restore
      working-directory: ./Easy-Logger-Sql
    - name: Build SQL
      run: dotnet build --configuration Release
      working-directory: ./Easy-Logger-Sql
